language: node_js
node_js:
- '8'
- '10'
script:
- npm run clean
- npm run build
cache: yarn
deploy:
  provider: s3
  access_key_id: AKIAJNC6KQX2VSP6G3JQ
  secret_access_key:
    secure: GSIO3vkSY1OojenFiIp2xm929zNWdkxAJVjprrEXmhXyMODxmO9ovY56eTWMIAD3AzRsCD3Irplaf7h1Qwvliswe4Tr4HwyKwhBOrH5V6adkc3e5Qml3B0oFGjIcG41G6OT5IWmthaTO2oMdY4UUAmQSvz5V0aVhiULtJ48QV3/DnipFC2CqZIyY5eAPlrgJ1cBsTGWogGro/3X6tjKAEhSER5aN/aGjVRPOBVVdkFpn4oPa1nqXcJElRF7KUjKvR+/zszPwwjEIKOZn+qSwnv3z0qvUpguiX+3k9ZQNt/7pO9A8PGom8WCRKCkg42GOuTVbTDWMk9Jzi4ApWi9aYe8pUsEqqqLrMJF/uO0BXhHM2B7Sq3dJDXEASmwr3davs6FV/6+WWuXIgShy2aN70Lp+uPaGz83eXDg5+4O2+SHy4YiFfHBDLvdjNshJnSy7GHxh0CjR8BDj5o9xiFTeQAHXZ6o2v5zW2BWv2dYdg8Bi0k7XQuiczwzrcw5ciZMMVa9Tz1UxsnijOZYlurZNJ4EM07ETzLttEMLSfPp20A1NJFxTh994ui/xJzuTh03opTc/Kt79OGZ5fbFWvKQQYXBXMKbUua3rzEqk9sVYrrTIGndP7soVb/QQhcp2DJZKcYpyjGfvr/87EcQrKkot4cquNPpkZ3HdtcfOUcBzOGo=
  bucket: iolandaparmeggiani.com
  local-dir: public
  skip_cleanup: true
  acl: public_read
  region: eu-central-1
  default_text_charset: utf-8
  on:
    repo: innocentiv/iolandaparmeggiani
    branch: master
